### ISSUE TITLE
Remove or upgrade nodejs

### ISSUE THREAD

**Issue by beruic** [mindrunner/docker-android-sdk#68]
I don't see why you install an old version of NodeJS.
Users of the images might as well install their own version.

Alternatively I'd recommend that you use nodesource PPAs with latest stable version of NodeJS.

I will gladly do a PR for any of these solutions.

**Comment by mindrunner** [comment]
Nodejs and npm are installed from official Ubuntu repos. Reasons why that might be outdated:

- Ubuntu uses an older version
- we are not using the most recent Ubuntu

I am not actively doing any Android stuff currently, hence not really maintaining those images. I cannot even remember why those images need node and npm to be honest. Maybe some cross platform dev SDKs are using it? I don't know.

We should probably remove it, since it has nothing to do with android development.

Also, it might be worth looking into bumping to Ubuntu 20.04 / 20.10 or something.

PRs appreciated!
