### ISSUE TITLE
Please start tagging versions

### ISSUE THREAD

**Issue by beruic** [mindrunner/docker-android-sdk#79]
The current approach of release has one vulnerability: You cannot revert to an earlier version if something goes wrong.

A change log would be nice too.

**Comment by mindrunner** [comment]
> In relation to this: Why does https://hub.docker.com/r/runmymind/docker-android-sdk seem to be updated almost every day, despite no changes being made?

Since the source sometimes does not change for Months, I am using regular builds to keep all dependencies up to date. This limits the probability of people using outdated software with security flaws. Daily builds, however, might be overkill for this project. I changed it to weekly now.


Furthermore, I added tags to images based on the git commits. If you want to stick for an older version you can do that now with: (e.g. `ubuntu-standalone-5fe1f87b`) where `ubuntu-standalone` is one of the four flavors and `5fe1f87b` is the short form of the git commit you want to use. 

Keep in mind, that the most recent commit will always be updated on a weekly base still.


I hope that lowers the pain.

**Comment by beruic** [comment]
@mindrunner We purge weekly, so that is just perfect.

I'm puzzling with whether it would be better to make it `{flavour}_{datetime}_{commit hash}`. This change will cause the following:

- We can always see when an image was built
- Building the same commit no longer overwrites the
- Tags are easily ordered chronologically
- Automatic deletion of tags can be done by both date and commit hash.

It can be done with either `CI_PIPELINE_CREATED_AT` or `CI_JOB_STARTED_AT` in GitLab CI.

However, I am not sure it is worth it, unless a good strategy for cleanup can be made.

**Comment by mindrunner** [comment]
@beruic is that still a thing?

**Comment by beruic** [comment]
@mindrunner I had to move projects internally. i'll hand this over to my successor @Teo27

**Comment by Teo27** [comment]
I believe the `{flavour}_{datetime}_{commit hash}` suggestion would benefit this project greatly due to the aforementioned reasons.

Thankfully, we haven't had any problems with the images. So our processes and requirements haven't changed.

**Comment by mindrunner** [comment]
There is a slight new tag structure now. I also updated the readme, but it is not complete yet. Just for reference here.
Have a look at https://hub.docker.com/repository/docker/runmymind/docker-android-sdk/tags?page=1&ordering=last_updated for all available tags.

You can pin to a specific commit id (`ubuntu-standalone-sha-943587d`)

Alternatively you can pin to a nightly build via date (`ubuntu-standalone-20230509`)

Would that fit your needs?


> Since the source sometimes does not change for Months, I am using regular builds to keep all dependencies up to date. This limits the probability of people using outdated software with security flaws. Daily builds, however, might be overkill for this project. I changed it to weekly now.

I would like go back to nightly builds for now. Would that be an issue for you?

**Comment by Teo27** [comment]
That works perfectly fine for us. And there should be no issues regarding the nightly builds.
